# Generated by Django 3.2.9 on 2021-11-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('mgmt_ip', models.CharField(max_length=12)),
                ('software_version', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('hardware_model', models.CharField(max_length=255)),
            ],
        ),
    ]
