# Generated by Django 3.2.9 on 2021-11-15 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_device_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(default='default_location', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 15, 57, 39, 617181, tzinfo=utc)),
        ),
    ]
