# Generated by Django 3.2.9 on 2021-11-15 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20211115_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 15, 58, 11, 81741, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
