# Generated by Django 3.2.9 on 2021-11-15 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20211115_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 17, 21, 53, 294410, tzinfo=utc)),
        ),
    ]
