# Generated by Django 3.2.9 on 2021-11-16 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_device_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 16, 0, 17, 49672, tzinfo=utc)),
        ),
    ]
