# Generated by Django 3.2.9 on 2021-11-17 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20211117_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 16, 37, 58, 246600, tzinfo=utc)),
        ),
    ]
