# Generated by Django 3.2.9 on 2021-11-17 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_device_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.CharField(default='Cisco', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 17, 9, 29, 179972, tzinfo=utc)),
        ),
    ]
