# Generated by Django 3.2.9 on 2021-11-18 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20211117_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 11, 10, 3, 658845, tzinfo=utc)),
        ),
    ]
